[package]
name = "sprocket-py-macros"
version = "0.1.1"
authors.workspace = true
description = "Macros that support Sprocket's Python bindings"
rust-version.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository = "https://github.com/stjude-rust-labs/sprocket/tree/main/crates/sprocket-py-macros"

[dependencies]
# Proc-macro interoperability
proc-macro2 = "1.0.107"
# Generate token streams from code
quote = "1.0.47"
# Parses token streams into syntax trees
syn = { version = "3.0.2", features = ["full", "extra-traits"] }

[dev-dependencies]
pretty_assertions.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true
