import typing as t


class Mode:
    FULL: Mode
    ONE_LINE: Mode

    def default() -> Mode: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: t.Any) -> bool: ...
