class Diagnostic:
    @staticmethod
    def error(message: str) -> Diagnostic: ...
    @staticmethod
    def warning(message: str) -> Diagnostic: ...
    @staticmethod
    def note(message: str) -> Diagnostic: ...
    def with_rule(self, rule: str) -> Diagnostic: ...
    def with_help(self, help: str) -> Diagnostic: ...
    def with_fix(self, fix: str) -> Diagnostic: ...
