[default]
# Enforce US English specifically
locale = "en-us"

[default.extend-words]
# Add words here to ignore them (case-sensitive)
ba = "ba"
bimap = "bimap"
caf = "caf"
Divable = "Divable"
FO = "FO"

[files]
# Ignore folders that don't need spellchecking
extend-exclude = [
    "target/",
    "Cargo.lock",
    ".git/",
    "*.bin",
    "*.js",
    "crates/wdl-engine/tests/workflows/concurrent-localization/",
    "crates/wdl-engine/tests/workflows/localization/",
    "crates/wdl-engine/tests/workflows/map-to-array/",
    "crates/wdl-engine/tests/workflows/pair-to-array/",
    "crates/gauntlet/",
    "crates/wdl-grammar/tests/parsing/**/*.tree",
    "crates/wdl-format/tests/format/ENCODE-DCC_chip-seq-pipeline/",
]
ignore-hidden = true
