//! Implementation of the config command.

use anyhow::Context;
use clap::Parser;
use clap::Subcommand;

use crate::commands::CommandError;
use crate::commands::CommandResult;
use crate::config::Config;

/// Arguments for the `config` subcommand.
#[derive(Parser, Debug, Clone)]
pub struct Args {
    /// Subcommand for the `config` command.
    #[command(subcommand)]
    command: ConfigSubcommand,
}

impl Args {
    /// Returns `true` if the subcommand is 'Init'.
    pub fn is_init(&self) -> bool {
        matches!(self.command, ConfigSubcommand::Init)
    }
}

/// Subcommands for the `config` command.
#[derive(Subcommand, Debug, Clone)]
pub enum ConfigSubcommand {
    /// Generates a default configuration file.
    Init,

    /// Displays the current configuration.
    Resolve(ResolveArgs),
}

/// Arguments for the `config resolve` subcommand.
#[derive(Parser, Debug, Clone)]
pub struct ResolveArgs {
    /// Unredacts any redacted secrets in the configuration.
    #[clap(long)]
    unredact: bool,
}

/// Header prepended to `sprocket config init` output.
const INIT_HEADER: &str = "\
# Sprocket configuration file.
#
# This file was generated by `sprocket config init` and contains the default
# values. Edit it to customize Sprocket's behavior, then save it as
# `sprocket.toml`.
#
# Lint and validation rules are configured under `[check.rules.<RuleId>]`. Each
# rule may set `severity` (one of `off`, `note`, `warning`, or `error`) and any
# parameters that apply to it. For example:
#
#     [check.rules.NamingConvention]
#     severity = \"error\"
#     allowed_names = [\"GATK\"]
#
# Run `sprocket explain <RuleId>` to see a rule's configurable parameters, or
# `sprocket explain --list-all-rules` to list every rule.
";

/// Runs the `config` command.
pub fn config(args: Args, mut config: Config) -> CommandResult<()> {
    let (config, header) = match args.command {
        ConfigSubcommand::Init => (Config::default(), Some(INIT_HEADER)),
        ConfigSubcommand::Resolve(args) => {
            // Redact any secrets unless explicitly requested not to
            if !args.unredact {
                config.run.engine = config.run.engine.redact();
            }

            (config, None)
        }
    };

    let serialized = toml_spanner::to_string(&config)
        .context("failed to serialize configuration")
        .map_err(CommandError::Single)?;

    match header {
        Some(header) => println!("{header}\n{serialized}"),
        None => println!("{serialized}"),
    }
    Ok(())
}
