//! Implementation of the `lock` subcommand.

use std::collections::BTreeSet;
use std::fs::OpenOptions;
use std::io::Write;
use std::path::Path;
use std::path::PathBuf;
use std::str::FromStr;

use anyhow::Context;
use anyhow::anyhow;
use clap::Parser;
use colored::Colorize;
use indicatif::ProgressStyle;
use tracing::Level;
use tracing::span;
use tracing::warn;
use tracing_indicatif::span_ext::IndicatifSpanExt;
use wdl::analysis::Diagnostics;
use wdl::ast::AstNode;
use wdl::ast::AstToken;
use wdl::ast::Diagnostic;
use wdl::ast::Severity;
use wdl::ast::Span;
use wdl::ast::SupportedVersion;
use wdl::ast::v1::Expr;
use wdl::ast::v1::LiteralExpr;
use wdl::ast::v1::LiteralString;
use wdl::ast::v1::RequirementsItem;
use wdl::ast::v1::RuntimeItem;
use wdl::ast::v1::TaskDefinition;
use wdl::ast::version::V1;
use wdl::diagnostics::DiagnosticCounts;
use wdl::diagnostics::Mode;
use wdl::diagnostics::emit_diagnostics;
use wdl::engine::config::DEFAULT_TASK_CONTAINER;
use wdl::engine::images::ImageDigests;
use wdl::engine::images::ImageOverrideMap;
use wdl::engine::v1::requirements::ImageSource;

use crate::Config;
use crate::analysis::Analysis;
use crate::analysis::Source;
use crate::commands::CommandError;
use crate::commands::CommandResult;
use crate::lock::file::LockFile;

/// Name for the lock file.
pub(crate) const LOCK_FILE: &str = "sprocket.lock";

/// Warning header for the lockfile.
const FILE_HEADER: &str = r#"# This file is automatically generated by `sprocket lock`.
# It is not intended for manual editing.
"#;

/// Arguments for the `lock` subcommand.
#[derive(Parser, Debug)]
pub struct Args {
    /// A source WDL document, directory, or URL.
    #[clap(value_name = "SOURCE")]
    pub source: Option<Source>,

    /// Require that all container images can produce a lockfile entry.
    ///
    /// By default, images that can't be determined (e.g., those with
    /// placeholders), will simply be skipped. This makes them a fatal
    /// error.
    #[clap(long)]
    pub strict: bool,

    /// Output directory for the lock file.
    #[clap(short, long, value_name = "DIR")]
    pub output: Option<PathBuf>,

    /// The report mode.
    #[arg(short = 'm', long, value_name = "MODE")]
    pub report_mode: Option<Mode>,
}

/// Create a "no container specified" diagnostic.
fn no_container(span: Span, version: SupportedVersion) -> Diagnostic {
    let section_name = if version >= SupportedVersion::V1(V1::Two) {
        "requirements"
    } else {
        "runtime"
    };

    Diagnostic::note("no container specified")
        .with_highlight(span)
        .with_help(
            "tasks should specify a container image, otherwise the engine's default will be used",
        )
        .with_fix(format!("consider adding a `{section_name}` section"))
}

/// Create a "container with placeholder" diagnostic.
fn container_with_placeholder(span: Span, strict: bool) -> Diagnostic {
    let severity = if strict {
        Severity::Error
    } else {
        Severity::Warning
    };

    Diagnostic::new(severity, "container with placeholder")
        .with_highlight(span)
        .with_help("lock entries cannot be generated for placeholder values")
}

/// Create an "unknown container source" diagnostic.
fn unknown_source(span: Span, strict: bool) -> Diagnostic {
    let severity = if strict {
        Severity::Error
    } else {
        Severity::Note
    };

    Diagnostic::new(severity, "unknown container source")
        .with_label("this will not be included in the lockfile", span)
}

/// Determine the container images that the `task` references.
fn task_container_images(
    task: TaskDefinition,
    version: SupportedVersion,
    strict: bool,
) -> (Vec<ImageSource>, Diagnostics) {
    fn check_string(
        expr: &Expr,
        s: &LiteralString,
        containers: &mut Vec<ImageSource>,
        diagnostics: &mut Diagnostics,
        strict: bool,
    ) {
        match s.text() {
            Some(text) => {
                let mut container = String::new();
                text.unescape_to(&mut container);

                let source = ImageSource::from_str(&container).expect("infallible");
                match source {
                    ImageSource::SifFile(_) => {}
                    ImageSource::Unknown(_) => {
                        diagnostics.add(unknown_source(expr.span(), strict));
                    }
                    ImageSource::Docker(ref image) | ImageSource::Oras(ref image) => {
                        if image.contains("@sha256:") {
                            // Nothing to do, already locked
                            return;
                        }

                        containers.push(source);
                    }
                    ImageSource::Library(ref image) => {
                        if image.contains(":sha256.") {
                            // Nothing to do, already locked
                            return;
                        }

                        containers.push(source);
                    }
                }
            }
            None => {
                diagnostics.add(container_with_placeholder(expr.span(), strict));
            }
        }
    }

    let expr = match task.requirements() {
        Some(requirements) => requirements
            .container()
            .and_then(|c| RequirementsItem::cast(c.inner().clone()))
            .map(|r| r.expr()),
        None => task
            .runtime()
            .and_then(|r| r.container())
            .and_then(|c| RuntimeItem::cast(c.inner().clone()))
            .map(|r| r.expr()),
    };

    let mut containers = Vec::new();
    let mut diagnostics = Diagnostics::default();
    let Some(expr) = expr else {
        // Otherwise we'll just fallback to the default.

        // SAFETY: Guaranteed to be a valid container spec
        containers.push(DEFAULT_TASK_CONTAINER.parse().unwrap());
        diagnostics.add(no_container(task.name().span(), version));
        return (containers, diagnostics);
    };

    match expr {
        Expr::Literal(LiteralExpr::String(ref s)) => {
            check_string(&expr, s, &mut containers, &mut diagnostics, strict);
        }
        Expr::Literal(LiteralExpr::Array(arr)) => {
            for e in arr.elements() {
                let Expr::Literal(LiteralExpr::String(s)) = &e else {
                    unreachable!("should be handled by validation");
                };

                check_string(&e, s, &mut containers, &mut diagnostics, strict);
            }
        }
        _ => {
            diagnostics.add(container_with_placeholder(expr.span(), strict));
            return (containers, diagnostics);
        }
    }

    (containers, diagnostics)
}

/// Context for the `lock` subcommand.
#[derive(Default)]
struct LockContext {
    /// The client for OCI-compatible registries, if necessary.
    oci_client: Option<crate::lock::oci::OciClient>,
    /// The client for Sylabs cloud images, if necessary.
    http_client: Option<reqwest::Client>,
    /// The set of images to resolve.
    images: BTreeSet<ImageSource>,
}

impl LockContext {
    /// Initialize the `LockContext` with the necessary clients.
    fn init(images: BTreeSet<ImageSource>) -> anyhow::Result<Self> {
        let mut oci_expected = false;
        let mut sylabs_expected = false;
        for image in &images {
            match image {
                ImageSource::Docker(_) | ImageSource::Oras(_) => oci_expected = true,
                ImageSource::Library(_) => sylabs_expected = true,
                ImageSource::SifFile(_) | ImageSource::Unknown(_) => {}
            }
        }

        let oci_client = if oci_expected {
            Some(crate::lock::oci::OciClient::new()?)
        } else {
            None
        };

        let http_client = if sylabs_expected {
            Some(
                reqwest::ClientBuilder::new()
                    .user_agent(crate::lock::USER_AGENT)
                    .build()?,
            )
        } else {
            None
        };

        Ok(Self {
            oci_client,
            http_client,
            images,
        })
    }

    /// Attempt to resolve the digests of all specified images.
    async fn resolve_digests(&mut self, colorize: bool) -> anyhow::Result<ImageOverrideMap> {
        let template = if colorize {
            "[{elapsed_precise:.cyan/blue}] {spinner:.cyan/blue} checking image {msg} ({pos}/{len})"
        } else {
            "[{elapsed_precise}] {spinner} checking image {msg} ({pos}/{len})"
        };

        let progress_bar = span!(Level::WARN, "progress");
        progress_bar.pb_set_style(&ProgressStyle::with_template(template).unwrap());
        progress_bar.pb_set_length(self.images.len().try_into().unwrap());
        progress_bar.pb_start();

        let mut map = ImageOverrideMap::new();

        for (index, source) in self.images.iter().enumerate() {
            progress_bar.pb_set_position(index.saturating_add(1).try_into().unwrap());
            progress_bar.pb_set_message(&format!("{source:#}").magenta());

            match source {
                ImageSource::Docker(_) | ImageSource::Oras(_) => {
                    let oci_image = source.try_into().expect("should convert");

                    let locked_source = crate::lock::oci::resolve_oci_image(
                        self.oci_client.as_mut().expect("should be set"),
                        oci_image,
                    )
                    .await?;

                    map.insert(source.clone(), ImageDigests::OciManifest(locked_source));
                }
                ImageSource::Library(image) => {
                    let Some((image, tag)) = image.rsplit_once(':') else {
                        return Err(anyhow!("image doesn't specify a tag"));
                    };

                    let digests = crate::lock::sylabs::resolve_sylabs_image(
                        self.http_client.as_ref().expect("should be set"),
                        image,
                        tag,
                    )
                    .await?;

                    map.insert(source.clone(), ImageDigests::PerArch(digests));
                }
                ImageSource::SifFile(_) | ImageSource::Unknown(_) => {
                    unreachable!("should be filtered out before")
                }
            }
        }

        Ok(map)
    }
}

/// Performs the `lock` command.
pub async fn lock(args: Args, config: Config, colorize: bool) -> CommandResult<()> {
    let report_mode = config.common.report_mode;
    let output_path = std::path::absolute(
        args.output
            .unwrap_or_else(|| PathBuf::from(std::path::Component::CurDir.as_os_str()))
            .join(LOCK_FILE),
    )
    .context("failed to determine path")?;

    let s = args.source.unwrap_or_default();
    let results = Analysis::default()
        .add_source(s)
        .fallback_version(config.common.wdl.fallback_version.into())
        .modules_config(config.modules.clone())
        .feature_flags(config.common.wdl.feature_flags)
        .ignore_filename(config.common.ignore_filename())
        .run(report_mode, colorize)
        .await
        .map_err(CommandError::from)?;

    let mut counts = DiagnosticCounts::default();
    let mut images: BTreeSet<ImageSource> = BTreeSet::new();
    for result in results {
        let path = result.document().path().to_string();
        let source = result.document().root().text().to_string();

        emit_diagnostics(
            &path,
            &source,
            result.document().diagnostics().filter(|d| {
                if d.severity() == Severity::Error {
                    counts.errors += 1;
                    return true;
                }

                false
            }),
            args.report_mode.unwrap_or_default(),
            colorize,
        )
        .context("failed to emit diagnostics")?;

        let doc = result.document();

        for task in doc
            .root()
            .ast_with_version_fallback(result.document().config().fallback_version())
            .as_v1()
            .expect("should be a v1 document")
            .tasks()
        {
            let (sources, diagnostics) =
                task_container_images(task, doc.version().unwrap(), args.strict);
            emit_diagnostics(
                &doc.path(),
                &doc.root().text().to_string(),
                diagnostics.iter(),
                args.report_mode.unwrap_or_default(),
                colorize,
            )?;

            images.extend(sources);
        }
    }

    if let Some(e) = counts.verify_no_errors() {
        return Err(e.into());
    }

    let mut context = LockContext::init(images)?;
    let resolved_images = context.resolve_digests(colorize).await?;

    if resolved_images.is_empty() {
        warn!("no applicable images were found");
        return Ok(());
    }

    let lock = LockFile::new_v1(resolved_images);
    let data = toml_spanner::to_string(&lock).context("failed to serialize lock contents")?;
    write_lock_file(&output_path, data).context("failed to create lock file")?;

    println!(
        "Generated container lockfile at: `{}`",
        output_path.display()
    );

    Ok(())
}

/// Write the lockfile to disk.
fn write_lock_file(path: &Path, data: String) -> anyhow::Result<()> {
    let mut f = OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .open(path)?;
    f.write_all(FILE_HEADER.as_bytes())?;
    f.write_all(data.as_bytes())?;
    Ok(())
}
