//! Test for the light/dark theme toggle.

use std::path::Path;
use std::time::Duration;

use anyhow::Context;
use anyhow::bail;
use thirtyfour::By;
use thirtyfour::Rect;
use thirtyfour::WebDriver;
use thirtyfour::WebElement;
use thirtyfour::prelude::ElementQueryable;
use thirtyfour::prelude::ElementWaitable;

use crate::UiTest;
use crate::WebDriverExt;

// Colors from wdl-doc/theme/src/colors.css
/// The expected background color of the dark theme.
const BACKGROUND_DARK: &str = "rgba(7, 10, 26, 1)";
/// The expected background color of the light theme.
const BACKGROUND_LIGHT: &str = "rgba(248, 249, 252, 1)";
/// The localStorage key generated by alpine.js.
const THEME_LOCALSTORAGE_KEY: &str = "_x_theme";
/// The name of the dark theme as it appears in localStorage. Quoted twice since
/// alpine.js stores it as a JSON string.
const THEME_DARK: &str = "\"dark\"";
/// The name of the dark theme as it appears in localStorage.
const THEME_LIGHT: &str = "\"light\"";

/// Test for the light/dark theme toggle.
pub struct ToggleTheme;

#[async_trait::async_trait]
impl UiTest for ToggleTheme {
    fn name(&self) -> &'static str {
        "toggle_theme"
    }

    async fn run(&self, driver: &mut WebDriver, _docs_path: &Path) -> anyhow::Result<()> {
        match driver
            .localstorage(THEME_LOCALSTORAGE_KEY)
            .await?
            .as_deref()
        {
            Some(THEME_DARK) => {}
            theme => bail!(
                "expected `localStorage.{THEME_LOCALSTORAGE_KEY}` to be '{THEME_DARK}', found: \
                 {theme:?}"
            ),
        }

        // Theme should be dark by default
        let bg = driver.find(By::ClassName("layout__container")).await?;
        let current_color = bg.css_value("background-color").await?;
        if current_color != BACKGROUND_DARK {
            bail!(
                "expected dark theme background color to be {BACKGROUND_DARK}, found \
                 {current_color}"
            );
        }

        let toggle_button = driver.find(By::Id("theme-toggle")).await?;
        toggle_button.click().await?;

        bg.wait_until()
            .wait(Duration::from_millis(10), Duration::from_millis(5))
            .condition(move |elem: WebElement| {
                let current_color = current_color.clone();
                async move {
                    let bg_color = elem.css_value("background-color").await?;
                    Ok(bg_color != current_color)
                }
            })
            .await?;

        if driver
            .localstorage(THEME_LOCALSTORAGE_KEY)
            .await?
            .as_deref()
            != Some(THEME_LIGHT)
        {
            bail!("expected light theme to be stored in `localStorage`");
        }

        let current_color = bg.css_value("background-color").await?;
        if current_color != BACKGROUND_LIGHT {
            bail!(
                "expected light theme background color to be {BACKGROUND_LIGHT}, found \
                 {current_color}"
            );
        }

        // The theme toggle is an icon-only button, so it must carry an
        // accessible label.
        let toggle_button = driver.find(By::Id("theme-toggle")).await?;
        match toggle_button.attr("aria-label").await?.as_deref() {
            Some("Switch theme") => {}
            label => bail!(
                "expected the theme toggle to have `aria-label=\"Switch theme\"`, found: {label:?}"
            ),
        }

        // The decorative source-card icon-only copy button on a declaration
        // page must be keyboard focusable.
        let base = driver.current_url().await?;
        let struct_page = base
            .join("employee/Employee-struct.html")
            .context("failed to build struct page url")?;
        driver.goto(struct_page.as_str()).await?;

        let copy = driver
            .query(By::ClassName("source-card__copy"))
            .wait(Duration::from_secs(10), Duration::from_millis(100))
            .first()
            .await?;
        let info = driver
            .execute(
                r#"
                const btn = document.querySelector('.source-card__copy');
                if (!btn) return { found: false };
                btn.focus();
                return {
                    found: true,
                    tag: btn.tagName,
                    tabIndex: btn.tabIndex,
                    active: document.activeElement === btn,
                    disabled: !!btn.disabled,
                };
                "#,
                Vec::new(),
            )
            .await?;
        let info = info.json();
        if !info["found"].as_bool().unwrap_or(false) {
            bail!("expected a `.source-card__copy` button on the struct page");
        }
        if info["tag"].as_str() != Some("BUTTON") {
            bail!(
                "expected the source copy control to be a `<button>`, found {:?}",
                info["tag"]
            );
        }
        if info["disabled"].as_bool().unwrap_or(true) {
            bail!("expected the source copy control to be enabled");
        }
        if info["tabIndex"].as_i64().unwrap_or(-1) < 0 {
            bail!(
                "expected the source copy control to be in the tab order, tabIndex was {:?}",
                info["tabIndex"]
            );
        }
        if !info["active"].as_bool().unwrap_or(false) {
            bail!("expected the source copy control to accept focus");
        }
        // Keep a reference to the copy button to silence unused warnings and to
        // assert it is still attached after focusing.
        drop(copy);

        // The right rail must be visible above the responsive breakpoint
        // (1280px) and hidden below it. Capture the original window rect so the
        // shared browser window can be restored reliably for later tests.
        let original_rect = driver.get_window_rect().await?;

        driver.set_window_rect(0, 0, 1400, 900).await?;
        if !right_rail_displayed(driver).await? {
            restore_window(driver, &original_rect).await?;
            bail!("expected the right rail to be visible above the responsive breakpoint");
        }

        driver.set_window_rect(0, 0, 1000, 900).await?;
        if right_rail_displayed(driver).await? {
            restore_window(driver, &original_rect).await?;
            bail!("expected the right rail to be hidden below the responsive breakpoint");
        }

        // Restore the shared browser window so later tests are unaffected.
        restore_window(driver, &original_rect).await?;

        Ok(())
    }
}

/// Returns whether the right rail is currently rendered (not `display: none`).
async fn right_rail_displayed(driver: &WebDriver) -> anyhow::Result<bool> {
    // Give the layout a moment to react to the window resize.
    for _ in 0..20 {
        let ret = driver
            .execute(
                r#"
                const el = document.querySelector('.layout__main-rail');
                if (!el) return null;
                return getComputedStyle(el).display !== 'none' && el.offsetParent !== null;
                "#,
                Vec::new(),
            )
            .await?;
        if let Some(displayed) = ret.json().as_bool() {
            return Ok(displayed);
        }
        tokio::time::sleep(Duration::from_millis(50)).await;
    }
    bail!("could not find the right rail element");
}

/// Restores the shared browser window to a previously captured rect so later
/// tests are unaffected by this test's resizing.
async fn restore_window(driver: &WebDriver, rect: &Rect) -> anyhow::Result<()> {
    driver
        .set_window_rect(rect.x, rect.y, rect.width as u32, rect.height as u32)
        .await?;
    Ok(())
}
