//! Tests for diagnostic baseline filtering in the LSP.

mod common;

use tower_lsp::lsp_types::WorkspaceDiagnosticReportResult;
use tower_lsp::lsp_types::WorkspaceDocumentDiagnosticReport;
use wdl_lint::Baseline;
use wdl_lint::BaselineEntry;

use crate::common::TestContext;

/// Extracts all diagnostic rule codes from a workspace diagnostic report.
fn diagnostic_codes(report: &WorkspaceDiagnosticReportResult) -> Vec<String> {
    let WorkspaceDiagnosticReportResult::Report(report) = report else {
        return Vec::new();
    };

    report
        .items
        .iter()
        .flat_map(|item| match item {
            WorkspaceDocumentDiagnosticReport::Full(full) => {
                full.full_document_diagnostic_report.items.clone()
            }
            WorkspaceDocumentDiagnosticReport::Unchanged(_) => Vec::new(),
        })
        .filter_map(|d| match d.code {
            Some(tower_lsp::lsp_types::NumberOrString::String(s)) => Some(s),
            _ => None,
        })
        .collect()
}

#[tokio::test]
async fn baseline_suppresses_matching_diagnostics() {
    // The baseline uses relative paths (as generated by the CLI). The LSP
    // will resolve documents to absolute paths. The path matching is
    // suffix-based so this still works.
    let baseline = Baseline::new(vec![
        BaselineEntry::new(
            "InputName",
            "source.wdl",
            "x",
            "declaration identifier must be at least 3 characters",
        ),
        BaselineEntry::new("UnusedInput", "source.wdl", "x", "unused input `x`"),
    ]);

    let mut ctx = TestContext::with_options(
        "baseline",
        wdl_lsp::ServerOptions {
            lint: wdl_lsp::LintOptions {
                enabled: true,
                ..Default::default()
            },
            baseline: Some(baseline),
            ..Default::default()
        },
    );
    let (_, report) = ctx.initialize().await;
    let codes = diagnostic_codes(&report);

    assert!(
        codes.contains(&"MetaSections".to_string()),
        "MetaSections should not be suppressed; got: {codes:?}"
    );
    assert!(
        !codes.contains(&"InputName".to_string()),
        "InputName should be suppressed; got: {codes:?}"
    );
    assert!(
        !codes.contains(&"UnusedInput".to_string()),
        "UnusedInput should be suppressed; got: {codes:?}"
    );
}

#[tokio::test]
async fn no_baseline_reports_all_diagnostics() {
    let mut ctx = TestContext::new("baseline");
    let (_, report) = ctx.initialize().await;
    let codes = diagnostic_codes(&report);

    assert!(
        codes.contains(&"MetaSections".to_string()),
        "MetaSections should be reported; got: {codes:?}"
    );
    assert!(
        codes.contains(&"InputName".to_string()),
        "InputName should be reported; got: {codes:?}"
    );
    assert!(
        codes.contains(&"UnusedInput".to_string()),
        "UnusedInput should be reported; got: {codes:?}"
    );
}
