import typing as t

class Span:
    start: int
    end: int

    def __new__(cls, start: int, len: int) -> Span: ...
    def len(self) -> int: ... # TODO: support len(Span)?
    def is_empty(self) -> bool: ...
    def contains(self, offset: int) -> bool: ...
    def intersect(self, other: Span) -> t.Optional[Span]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: t.Any) -> bool: ...
    def __lt__(self, other: Span) -> bool: ...
    def __gt__(self, other: Span) -> bool: ...
    def __le__(self, other: Span) -> bool: ...
    def __ge__(self, other: Span) -> bool: ...

class Severity:
    ERROR: Severity
    WARNING: Severity
    NOTE: Severity

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: t.Any) -> bool: ...
    def __lt__(self, other: Severity) -> bool: ...
    def __gt__(self, other: Severity) -> bool: ...
    def __le__(self, other: Severity) -> bool: ...
    def __ge__(self, other: Severity) -> bool: ...

class Diagnostic:
    @staticmethod
    def error(message: str) -> Diagnostic: ...
    @staticmethod
    def warning(message: str) -> Diagnostic: ...
    @staticmethod
    def note(message: str) -> Diagnostic: ...
    def with_rule(self, rule: str) -> Diagnostic: ...
    def with_help(self, help: str) -> Diagnostic: ...
    def with_fix(self, fix: str) -> Diagnostic: ...
    def with_highlight(self, span: Span) -> Diagnostic: ...
    def with_label(self, message: str, span: Span) -> Diagnostic: ...
    def with_severity(self, severity: Severity) -> Diagnostic: ...
    def rule(self) -> t.Optional[str]: ...
    def severity(self) -> Severity: ...
    def message(self) -> str: ...
    def fix(self) -> t.Optional[str]: ...
    def labels(self) -> list[Label]: ...
    def __eq__(self, other: t.Any) -> bool: ...
    def __lt__(self, other: Diagnostic) -> bool: ...
    def __gt__(self, other: Diagnostic) -> bool: ...
    def __le__(self, other: Diagnostic) -> bool: ...
    def __ge__(self, other: Diagnostic) -> bool: ...

class Label:
    message: str
    span: Span

    def __new__(cls, message: str, span: Span) -> Label: ...
    def __eq__(self, other: t.Any) -> bool: ...
    def __lt__(self, other: Label) -> bool: ...
    def __gt__(self, other: Label) -> bool: ...
    def __le__(self, other: Label) -> bool: ...
    def __ge__(self, other: Label) -> bool: ...
