import typing

@typing.final
class Diagnostic:
    rule: str | None
    severity: Severity
    message: str
    help: str | None
    fix: str | None
    labels: list[Label]

    @staticmethod
    def error(message: str) -> Diagnostic: ...
    @staticmethod
    def warning(message: str) -> Diagnostic: ...
    @staticmethod
    def note(message: str) -> Diagnostic: ...
    def with_rule(self, rule: str) -> Diagnostic: ...
    def with_help(self, help: str) -> Diagnostic: ...
    def with_fix(self, fix: str) -> Diagnostic: ...
    def with_highlight(self, span: Span) -> Diagnostic: ...
    def with_label(self, message: str, span: Span) -> Diagnostic: ...
    def with_severity(self, severity: Severity) -> Diagnostic: ...
    def __lt__(self, other: typing.Any, /) -> bool: ...
    def __le__(self, other: typing.Any, /) -> bool: ...
    def __gt__(self, other: typing.Any, /) -> bool: ...
    def __ge__(self, other: typing.Any, /) -> bool: ...

@typing.final
class Label:
    message: str
    span: Span

    def __new__(cls, message: str, span: Span) -> Label: ...

@typing.final
class Severity:
    ERROR: Severity
    WARNING: Severity
    NOTE: Severity

    def __lt__(self, other: typing.Any, /) -> bool: ...
    def __le__(self, other: typing.Any, /) -> bool: ...
    def __gt__(self, other: typing.Any, /) -> bool: ...
    def __ge__(self, other: typing.Any, /) -> bool: ...

@typing.final
class Span:
    start: int
    end: int

    def __new__(cls, start: int, len: int) -> Span: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def contains(self, offset: int) -> bool: ...
    def intersect(self, other: Span) -> Span | None: ...
    def __len__(self) -> int: ...
    def __lt__(self, other: typing.Any, /) -> bool: ...
    def __le__(self, other: typing.Any, /) -> bool: ...
    def __gt__(self, other: typing.Any, /) -> bool: ...
    def __ge__(self, other: typing.Any, /) -> bool: ...

__all__ = ["Diagnostic", "Label", "Severity", "Span"]
