name: Bump crate versions

on:
  workflow_dispatch:
    inputs:
      crate:
        description: Crate to bump (anything which depends on this crate will also be bumped)
        type: choice
        default: wdl-grammar
        options:
          - wdl-grammar
          - wdl-ast
          - wdl-format
          - wdl-lint
          - wdl-analysis
          - wdl-doc
          - wdl-engine
          - wdl-lsp
          - wdl-cli
          - wdl
          - sprocket

jobs:
  bump:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - run: cargo --locked run --release --bin ci -- bump --crates-to-bump ${{ inputs.crate }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: chore/bump
          title: "release: bump crate versions"
          commit-message: "release: bump crate versions"
