name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  RUST_BACKTRACE: full
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}
  IN_CI: 1
  # Only include the debug info necessary for backtraces (file names and line numbers). Any extra
  # debug info provided by `debuginfo=1` or `debuginfo=2` require an interactive debugger like
  # `lldb` or `gdb`.
  RUSTFLAGS: -C debuginfo=line-tables-only

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Spell Check Repo
        uses: crate-ci/typos@v1.46.3

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update Rust
        run: rustup update nightly && rustup default nightly
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Check source code formatting
        run: cargo --locked fmt -- --check

  sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update Rust
        run: rustup update stable
      - name: Install `cargo-sort`
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-sort@2
      - name: Check for sorted `Cargo.toml`
        run: cargo --locked sort -w --check

  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - name: Install clippy
        run: rustup component add clippy
      - name: Check source code for lints
        run: cargo --locked clippy --workspace --tests --all-features -- --deny warnings

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/install-shellcheck
      - name: Update Rust
        run: rustup update stable && rustup default stable && rustup component add llvm-tools

      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          # Only save cache on the main branch, as caches saved on other branches cannot be shared.
          # <https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching#restrictions-for-accessing-a-cache>
          save-if: ${{ github.ref == 'refs/heads/main' }}
          # Do not cache bins, as we already install pre-built binaries.
          cache-bin: false

      - name: Install cargo-llvm-cov and cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: |
            cargo-llvm-cov@0.8
            nextest@0.9

      # Pre-warm the npx cache so parallel tests don't race to install it.
      - name: Install Pagefind
        if: runner.os == 'Linux'
        run: npx -y pagefind@1.5.0 --help

      # TODO: nextest doesn't support doc tests yet (https://github.com/nextest-rs/nextest/issues/16)
      - name: Run tests
        shell: bash
        run: cargo llvm-cov nextest --profile=ci --workspace --locked --all-targets --all-features --no-fail-fast --codecov --output-path codecov.json && cargo test --workspace --doc

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.json
          fail_ci_if_error: true
          exclude: "crates/gauntlet"

  engine-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/install-shellcheck
      - name: Update Rust
        run: rustup update stable && rustup default stable && rustup component add llvm-tools

      - name: Install cargo-llvm-cov and cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: |
            cargo-llvm-cov@0.8
            nextest@0.9

      # See the `test` job
      - name: Install Pagefind
        run: npx -y pagefind@1.5.0 --help

      - name: Pull test images
        if: runner.os == 'Linux'
        run: |
          docker pull ubuntu:latest
          docker pull ubuntu:focal
          docker pull ghcr.io/multiqc/multiqc:v1.31
          docker pull ghcr.io/stjudecloud/util:3.0.1
          docker pull alpine:latest
      - name: Run tests
        shell: bash
        run: |
          if [[ "${{ runner.os }}" != "Linux" ]]; then
            export RUSTFLAGS="--cfg docker_tests_disabled ${RUSTFLAGS}"
          fi
          cargo llvm-cov nextest --profile=ci --ignore-default-filter -E "not (kind(bench))" --locked -p wdl-engine -p sprocket --all-features --no-fail-fast --codecov --output-path codecov.json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.json
          fail_ci_if_error: true

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - run: cargo --locked doc

  gauntlet:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - run: git config --global core.autocrlf false
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - run: cargo --locked run -p gauntlet --release --bin gauntlet

  arena:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/install-shellcheck
      - run: git config --global core.autocrlf false
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - run: cargo --locked run -p gauntlet --release --bin gauntlet -- --arena

  workspace-lints-enabled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - name: Install `cargo-workspace-lints`
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-workspace-lints@0.1
      - run: cargo --locked workspace-lints

  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - name: Install cargo-deny
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny@0.19
      - run: cargo --locked deny check

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - name: Install cargo-msrv
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-msrv@0.19
      - name: Verify the MSRV
        working-directory: ./crates/wdl
        run: cargo --locked msrv verify --output-format minimal --all-features

  udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update Rust
        run: rustup update nightly && rustup default nightly
      - name: Install cargo-udeps
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-udeps@0.1
      - name: Ensure no unused dependencies
        run: cargo --locked udeps
