name: Adds labels

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  GH_TOKEN: ${{ github.token }}
  GH_REPO: ${{ github.repository }}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add labels
        continue-on-error: true
        run: |
          PR_NUMBER=$(gh pr list --search "${{ github.event.workflow_run.head_sha }}" --state all --json number --jq '.[0].number')

          if [[ ! "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
            echo "No PR found for this commit. Exiting."
            exit 0
          fi

          if [[ ${{ github.event.workflow_run.conclusion }} == "success" ]]; then
            gh pr edit $PR_NUMBER --remove-label "S-awaiting-pass-CI"
          else
            gh pr edit $PR_NUMBER --add-label "S-awaiting-pass-CI"
          fi
