name: Release WDL crates

on:
  push:
    tags:
      - wdl-v*

jobs:
  release_wdl:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - run: cargo --locked run --release --bin ci -- publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
